<?php
namespace Omnipay\Enzona\Message\PaymentAPI\Commands\CreatePayment;

// This is a autogenerated file:PaymentInfo

class Item {
    public int $quantity; // json:quantity Required
    public float $price; // json:price Required
    public string $name; // json:name Required
    public string $description; // json:description Required
    public float $tax; // json:tax Required

    /**
     * @param int $quantity
     * @param float $price
     * @param string $name
     * @param string $description
     * @param float $tax
     */
    public function __construct(int $quantity, float $price, string $name, string $description, float $tax) {
        $this->quantity = $quantity;
        $this->price = $price;
        $this->name = $name;
        $this->description = $description;
        $this->tax = $tax;
    }
}

